### ISSUE TITLE
center sponsor logos inside their cells in the table

### ISSUE THREAD

**Issue by securelyfitz** [BSidesPDX/bsidespdx.org#10]

**Comment by koronkowy** [comment]
https://github.com/BSidesPDX/bsidespdx.org/pull/12
My recent pull request should solve this issue.

**Comment by tophertimzen** [comment]
Closed in https://github.com/BSidesPDX/bsidespdx.org/commit/28550e2ecb741d60d44a7607846771832361bc8a
