### ISSUE TITLE
figure out how to link mailchimp emails to the recent news feed, manually if neccessary...

### ISSUE THREAD

**Issue by securelyfitz** [BSidesPDX/bsidespdx.org#11]

**Comment by koronkowy** [comment]
@securelyfitz Is this still functionality that you want?
@btrimbo Same question for you, is this functionality that you would find valuable to the website / org / your job?

**Comment by btrimbo** [comment]
Fresh content always improves click generation. If the newsfeed is curated properly with interesting information, it would be good.

**Comment by koronkowy** [comment]
@btrimbo It would be your responsibility to manage the content, as it will be directly importing from mailchimp that you orchestrate. This means that posts and content pushed through mailchimp would have to be suitable / designed in a way that their content could be on the website as well in this proposed feed.
