### ISSUE TITLE
Migrate site over to support 2019

### ISSUE THREAD

**Issue by tophertimzen** [BSidesPDX/bsidespdx.org#19]
1. Update index
1. Update past events page
1. Move /events to 2019 and pre-create placeholders for content
1. Update venue
1. Update CFP

**Comment by sparklespdx** [comment]
Need an endpoint / service for event registration, @securelyfitz to follow up.

**Comment by tophertimzen** [comment]
Closed in https://github.com/BSidesPDX/bsidespdx.org/pull/26
