### ISSUE TITLE
CFP Board is under 2019 and CFP in navigation - redundancy

### ISSUE THREAD

**Issue by koronkowy** [BSidesPDX/bsidespdx.org#29]
![Captureee](https://user-images.githubusercontent.com/43873379/59630505-4ed02b80-90fa-11e9-9cae-1212f08145fb.PNG)
![Captureeeeeee](https://user-images.githubusercontent.com/43873379/59630506-4f68c200-90fa-11e9-9dc3-6bcf3bdc1539.PNG)
Is it necessary to have the CFP board show up in both dropdowns?

I suggest removing it from one or the other.

**Comment by tophertimzen** [comment]
This was done on purpose so we could easily show people via the CFP who the Review Board is and then each year in `/events/` we also have the review board. I don't see this as an issue from a UX perspective. 

Going to close this, but does anyone else want to weigh in?
