### ISSUE TITLE
Volunteer info on site

### ISSUE THREAD

**Issue by koronkowy** [BSidesPDX/bsidespdx.org#31]
Spoke with our 2019 Volunteer coordinator about getting Volunteer info up on the website.
There are many pros, like it would be nice if we could have a volunteer section that I can direct sponsors who ask about volunteer opportunities to on our website vs. sending just that raw link to the web form.

1) We should have a page with a link to the gsuite form: https://forms.gle/fHyQpYFYrX5zJ26N6
2) Also having a note that the volunteer coordinator can be contacted directly at: shady@bsidespdx.org on the page would be great.
3) Some verbiage around opportunities, getting set up on the mailing list, thanking people for their interest, tell them to look for more info closer to the date, etc. Suggest other ways they can get involved, like donating (link out to sponsorship).

**Comment by tophertimzen** [comment]
This was closed in https://github.com/BSidesPDX/bsidespdx.org/commit/d803bf0bb25cfb3c6acb08342483ea2963af532d
