### ISSUE TITLE
embed registration on registration.html page

### ISSUE THREAD

**Issue by securelyfitz** [BSidesPDX/bsidespdx.org#9]
right now we've got a link to eventzilla. i pasted the code eventzilla gave me but i think jekyll is wrapping it in another frame. Anyone want to take a look and make it not look so bad?

**Comment by koronkowy** [comment]
Once we know what payment system is going to happen and how @securelyfitz is orchestrating this, let's get this up.

**Comment by securelyfitz** [comment]
added the url and some text. Would be nice to embed it if possible, if not then maybe pretty it up a bit?
-joe
